name: Publish to Nuget

on:
  push:
    tags: [ 'v*' ]
  
jobs:
  release:
    runs-on: windows-latest

    steps:    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    
    - name: Extract version from tag
      uses: Amadevus/pwsh-script@v2.0.1
      id: getVersion
      with:
        script: '("${{ steps.tag.outputs.tag }}").Split("v")[1]'
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and pack
      run: msbuild -t:pack /restore /p:Configuration=Release /p:Version=${{ steps.getVersion.outputs.result }}
    
    - name: Publish
      run: nuget push bin/Release/Wokhan.UI.${{ steps.getVersion.output .result }}.nupkg -ApiKey ${{ secrets.nuget_apikey }} -Source https://api.nuget.org/v3/index.json
